### ISSUE TITLE
Example module error : prevented in-tree build considerd bad-practice

### ISSUE THREAD

**Issue by Dantali0n** [guruofquality/gras#119]
Using the provided build instructions the cmake ../ command run from the build folder fails on a error in
example_module_location with the following message: `Prevented in-tree build. this is bad practice.`

**Comment by guruofquality** [comment]
I'm not sure why that’s happening, you might try simply removing the check from the CMakeLists.txt... But just so you know, this project GRAS is 100% abandoned. I unfortunately, and to my great dismay, had to stop working on it. So I started a new project from scratch almost 3 years ago and whatever features that you might be interested in -- I'm sure that I maintain them now in Pothos: https://github.com/pothosware/pothos/wiki

**Comment by Dantali0n** [comment]
Thanks for the information ill be sure to use Pothos instead.
