### ISSUE TITLE
work return value

### ISSUE THREAD

**Issue by guruofquality** [guruofquality/gras#4]
Currently, whats hacked into the work return:
- -2 = produced
- -1 = mark done
- >= check input, accumulate or mark done

This cant stay. We need a formal API way to mark the block done, a way to NOP, and way to conditionally mark a block done when input is done. Any others?

gr_block.cc will have to be updated to reflect this new API

**Comment by riveridea** [comment]
Hello Josh,

What is "NOP"? No output produced?  Currently I have a block that does not
produce the output items until enough input items is received. But for each
input item (size is like 64 complex samples), it still needs to generate a
temporal result for accumulating. So before the final output is generated,
I always return -2.

On Mon, Nov 5, 2012 at 12:04 AM, Josh Blum notifications@github.com wrote:

> Currently, whats hacked into the work return:
> - -2 = produced
> - -1 = mark done
> - >= check input, accumulate or mark done
> 
> This cant stay. We need a formal API way to mark the block done, a way to
> NOP, and way to conditionally mark a block done when input is done. Any
> others?
> 
> gr_block.cc will have to be updated to reflect this new API
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/guruofquality/gras/issues/4.

## 

Alex,
_Dreams can come true – just believe._

**Comment by guruofquality** [comment]
work is now declared void, and failure and done states now have formal APIs
- mark done, input fail, output fail
- see #16 for continued issues
