### ISSUE TITLE
Error running cmake.

### ISSUE THREAD

**Issue by benreynwar** [guruofquality/gras#43]
Either I'm doing something stupid, or cmake isn't working.

Log of output at:
https://gist.github.com/4685781

**Comment by guruofquality** [comment]
Did you init/update submodules?

Update so you have this commit with the helpful message
https://github.com/guruofquality/gras/commit/5affe12349739559c8ce58e62df843f9dce49b64

Also https://github.com/guruofquality/gras/wiki/Build

**Comment by benreynwar** [comment]
Yeah, apparently I should have read your build instructions from the top.
