### ISSUE TITLE
Problem with Theron when installing gras

### ISSUE THREAD

**Issue by alfayez** [guruofquality/gras#46]
hey guru, i'm having a problem installing gras.  I've followed the steps from the wiki and the configuration seems going well.

cmake ../
make

from within the gras directory but when I run make Theron is complaining about some non-declared boost functions ... I know boost is working since gnuradio is working.  Can it be a boost version issue?  I'm using 1.40

The following is the output from the configure and install stages:
https://gist.github.com/alfayez/4993143

thanks

**Comment by guruofquality** [comment]
Reposing comment:
Also, maybe I should move this bug to the my theron github...

---

FYI - here is a standalone Theron repo w/ CMakeLists.txt if we need to pursue this more
https://github.com/guruofquality/Theron

The boost files in Theron are copied from boost to implement the atomic stuff - so its kind of a boost bug, but not a bug in the boost on your system

It looks like the enum memory_order is not defined. This might be that this is c++11 and you have an older gcc. Interestingly boost on my system offers a boost::memory_order as a c++11x0 whatever compatibility.

A quick fix might be to edit boost/atomic/platform.hpp so it includes gcc-cas (the more generic implementation for gcc).

Can you report your gcc version?

**Comment by guruofquality** [comment]
to merge: https://github.com/guruofquality/Theron/commit/5adee7218d2b574743cc874e2684181fd53ea691
