### ISSUE TITLE
gras and gnuradio issue with ubuntu 10.04

### ISSUE THREAD

**Issue by alfayez** [guruofquality/gras#48]
just pulled the new updates and i'm able to install things however i'm getting runtime linking errors when i try to run things ... the following are two examples when i try to run grextra and gr-audio examples:

alfayez@alfayez-laptop-ubuntu:~/workspace/gnuradio-gras/gras/grextras/tests$ python noise_source_test.py 
Traceback (most recent call last):
  File "noise_source_test.py", line 24, in <module>
    import grextras
  File "/opt/usr/gras/lib/python2.6/dist-packages/grextras/**init**.py", line 6, in <module>
    from GrExtras_Misc import *
  File "/opt/usr/gras/lib/python2.6/dist-packages/grextras/GrExtras_Misc.py", line 24, in <module>
    _GrExtras_Misc = swig_import_helper()
  File "/opt/usr/gras/lib/python2.6/dist-packages/grextras/GrExtras_Misc.py", line 20, in swig_import_helper
    _mod = imp.load_module('_GrExtras_Misc', fp, pathname, description)
ImportError: /opt/usr/gras/lib/libgrextras.so.0.0.0: undefined symbol: volk_32f_x2_multiply_32f

alfayez@alfayez-laptop-ubuntu:~/workspace/gnuradio-gras/gras/gnuradio/gr-audio/examples/python$ ./dial_tone.py 
Traceback (most recent call last):
  File "./dial_tone.py", line 23, in <module>
    from gnuradio import gr
  File "/opt/usr/gras/lib/python2.6/dist-packages/gnuradio/gr/**init**.py", line 27, in <module>
    from gnuradio_core import *
  File "/opt/usr/gras/lib/python2.6/dist-packages/gnuradio/gr/gnuradio_core.py", line 23, in <module>
    from gnuradio_core_runtime import *
  File "/opt/usr/gras/lib/python2.6/dist-packages/gnuradio/gr/gnuradio_core_runtime.py", line 24, in <module>
    _gnuradio_core_runtime = swig_import_helper()
  File "/opt/usr/gras/lib/python2.6/dist-packages/gnuradio/gr/gnuradio_core_runtime.py", line 20, in swig_import_helper
    _mod = imp.load_module('_gnuradio_core_runtime', fp, pathname, description)

**Comment by guruofquality** [comment]
On 02/23/2013 12:25 PM, Almohanad (Al) Fayez wrote:

> just pulled the new updates and i'm able to install things however
> i'm getting runtime linking errors when i try to run things ... the
> following are two examples when i try to run grextra and gr-audio
> examples:
> 
> alfayez@alfayez-laptop-ubuntu:~/workspace/gnuradio-gras/gras/grextras/tests$
> python noise_source_test.py Traceback (most recent call last): File
> "noise_source_test.py", line 24, in <module> import grextras File
> "/opt/usr/gras/lib/python2.6/dist-packages/grextras/**init**.py",
> line 6, in <module> from GrExtras_Misc import \* File
> "/opt/usr/gras/lib/python2.6/dist-packages/grextras/GrExtras_Misc.py",
> line 24, in <module> _GrExtras_Misc = swig_import_helper() File
> "/opt/usr/gras/lib/python2.6/dist-packages/grextras/GrExtras_Misc.py",
> line 20, in swig_import_helper _mod =
> imp.load_module('_GrExtras_Misc', fp, pathname, description) 
> ImportError: /opt/usr/gras/lib/libgrextras.so.0.0.0: undefined
> symbol: volk_32f_x2_multiply_32f
> 
> alfayez@alfayez-laptop-ubuntu:~/workspace/gnuradio-gras/gras/gnuradio/gr-audio/examples/python$
> ./dial_tone.py Traceback (most recent call last): File
> "./dial_tone.py", line 23, in <module> from gnuradio import gr File
> "/opt/usr/gras/lib/python2.6/dist-packages/gnuradio/gr/**init**.py",
> line 27, in <module> from gnuradio_core import \* File
> "/opt/usr/gras/lib/python2.6/dist-packages/gnuradio/gr/gnuradio_core.py",
> line 23, in <module> from gnuradio_core_runtime import \* File
> "/opt/usr/gras/lib/python2.6/dist-packages/gnuradio/gr/gnuradio_core_runtime.py",
> line 24, in <module> _gnuradio_core_runtime = swig_import_helper() 
> File
> "/opt/usr/gras/lib/python2.6/dist-packages/gnuradio/gr/gnuradio_core_runtime.py",
> line 20, in swig_import_helper _mod =
> imp.load_module('_gnuradio_core_runtime', fp, pathname, description)

Not seeing either on my ubuntu 10.04 x86 vm

last commit on gnuradio df9bcf4297f0da202d28f9cdf1efd5bf8167d719
last commit on gras c14550afef3d3c3086c92315ea16a7b5bfa8ffa6

**Comment by alfayez** [comment]
I rm'ed the whole directory and started from scratch and made sure that I'm using the latest commits, same hashes you indicated, however the problem is still there.  Just realized that it's not passing "make test" please check the included output

alfayez@alfayez-laptop-ubuntu:~/workspace/gnuradio-gras/gras/build$ make test
Running tests...
Test project /home/alfayez/workspace/gnuradio-gras/gras/build
        Start   1: basic_test
  1/200 Test   #1: basic_test .......................   Passed    0.01 sec
        Start   2: serialize_test
  2/200 Test   #2: serialize_test ...................   Passed    0.01 sec
        Start   3: basic_types_test
  3/200 Test   #3: basic_types_test .................   Passed    0.13 sec
        Start   4: container_types_test
  4/200 Test   #4: container_types_test .............**_Failed    0.11 sec
        Start   5: operator_overloads_test
  5/200 Test   #5: operator_overloads_test ..........   Passed    0.11 sec
        Start   6: pool_test
  6/200 Test   #6: pool_test ........................   Passed    0.11 sec
        Start   7: numeric_array_test
  7/200 Test   #7: numeric_array_test ...............   Passed    0.11 sec
        Start   8: custom_type_test
  8/200 Test   #8: custom_type_test .................   Passed    0.12 sec
        Start   9: block_test
  9/200 Test   #9: block_test .......................**_Failed    0.14 sec
        Start  10: hier_block_test
 10/200 Test  #10: hier_block_test ..................   Passed    0.12 sec
        Start  11: thread_pool_test
 11/200 Test  #11: thread_pool_test .................   Passed    0.18 sec
        Start  12: sbuffer_test
 12/200 Test  #12: sbuffer_test .....................   Passed    0.12 sec
        Start  13: qa_volk_test_all
 13/200 Test  #13: qa_volk_test_all .................   Passed    1.29 sec
        Start  14: gruel-test
 14/200 Test  #14: gruel-test .......................   Passed    1.70 sec
        Start  15: qa_pmt
 15/200 Test  #15: qa_pmt ...........................   Passed    0.03 sec
        Start  16: gr-core-reed-solomon-test
 16/200 Test  #16: gr-core-reed-solomon-test ........   Passed    0.08 sec
        Start  17: gr-core-test-all
 17/200 Test  #17: gr-core-test-all .................   Passed    8.61 sec
        Start  18: qa_vector_sink_source
 18/200 Test  #18: qa_vector_sink_source ............_**Failed    0.36 sec
        Start  19: qa_boolean_operators
 19/200 Test  #19: qa_boolean_operators .............   Passed    0.76 sec
        Start  20: qa_skiphead
 20/200 Test  #20: qa_skiphead ......................   Passed    0.99 sec
        Start  21: qa_fft_filter
 21/200 Test  #21: qa_fft_filter ....................   Passed    7.61 sec
        Start  22: qa_sig_source
 22/200 Test  #22: qa_sig_source ....................   Passed    0.75 sec
        Start  23: qa_max
 23/200 Test  #23: qa_max ...........................   Passed    0.32 sec
        Start  24: qa_tag_debug
 24/200 Test  #24: qa_tag_debug .....................   Passed    0.30 sec
        Start  25: qa_packed_to_unpacked
 25/200 Test  #25: qa_packed_to_unpacked ............   Passed    1.14 sec
        Start  26: qa_pll_freqdet
 26/200 Test  #26: qa_pll_freqdet ...................   Passed    0.28 sec
        Start  27: qa_kludge_copy
 27/200 Test  #27: qa_kludge_copy ...................   Passed    0.93 sec
        Start  28: qa_scrambler
 28/200 Test  #28: qa_scrambler .....................   Passed    0.35 sec
        Start  29: qa_fft
 29/200 Test  #29: qa_fft ...........................   Passed    0.39 sec
        Start  30: qa_pn_correlator_cc
 30/200 Test  #30: qa_pn_correlator_cc ..............   Passed    0.36 sec
        Start  31: qa_pll_carriertracking
 31/200 Test  #31: qa_pll_carriertracking ...........   Passed    0.29 sec
        Start  32: qa_hilbert
*_\* glibc detected **\* /usr/bin/python2.6: malloc(): memory corruption: 0x092bb728 ***

**Comment by guruofquality** [comment]
On 02/23/2013 06:10 PM, Almohanad (Al) Fayez wrote:

> I rm'ed the whole directory and started from scratch and made sure
> that I'm using the latest commits, same hashes you indicated, however
> the problem is still there.  Just realized that it's not passing
> "make test" please check the included output
> 
> **\* glibc detected **\* /usr/bin/python2.6: malloc(): memory
> corruption: 0x092bb728 ***

I did see this error on my VM. It seems not to be tied to a particular
test, more like a thing of random chance.

Its interesting that at this point, windows has been better behaved than
ubuntu 10.04 :-)

I'm building w/ debug mode now

**Comment by alfayez** [comment]
guru, I fixed it! and if you don't mind me tooting my own horn is a great solution indeed ... 

1- backup everything that's important
2- upgrade to ubuntu 12.04
3- reinstall gras
4- enjoy eternal bliss

I was done keeping up with 10.04 and the upgrade was surprisingly completely painless and smooth ... maybe you should just deprecate 10.04 :) besides I was seeing some warning that were making feel uncomfortable and insecure so i think this was the right move 

you should tell Ben to do the same and sweep this bug under the rug!

**Comment by guruofquality** [comment]
On 02/24/2013 01:32 AM, Almohanad (Al) Fayez wrote:

> guru, I fixed it! and if you don't mind me tooting my own horn is a
> great solution indeed ...
> 
> 1- backup everything that's important 2- upgrade to ubuntu 12.04 3-
> reinstall gras 4- enjoy eternal bliss

FWIW, the container_types_test fail was a swig issue I had to work
around. And... The python2.6: malloc(): memory corruption may as well be
a swig issue. I may never figure this one out.

Putting a 3 year old OS to rest sounds good to me. If I see the bugs
show up on other platforms I will still want to fix them. But if its a
non issue, then I can get back to making my scheduler status monitor.
